# Form implementation generated from reading ui file './QTUI/Cover.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 540)
        self.label_image = QtWidgets.QLabel(parent=Form)
        self.label_image.setGeometry(QtCore.QRect(80, 10, 640, 360))
        self.label_image.setStyleSheet("border: 1px solid; \n"
"border-color: rgb(202, 202, 202);")
        self.label_image.setObjectName("label_image")
        self.pushButton_set_image = QtWidgets.QPushButton(parent=Form)
        self.pushButton_set_image.setGeometry(QtCore.QRect(90, 470, 161, 31))
        self.pushButton_set_image.setObjectName("pushButton_set_image")
        self.checkBox_display_title = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_display_title.setGeometry(QtCore.QRect(90, 380, 71, 31))
        self.checkBox_display_title.setChecked(True)
        self.checkBox_display_title.setObjectName("checkBox_display_title")
        self.checkBox_display_resolution = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_display_resolution.setGeometry(QtCore.QRect(170, 380, 111, 31))
        self.checkBox_display_resolution.setChecked(True)
        self.checkBox_display_resolution.setObjectName("checkBox_display_resolution")
        self.checkBox_display_date = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_display_date.setGeometry(QtCore.QRect(290, 380, 61, 31))
        self.checkBox_display_date.setChecked(True)
        self.checkBox_display_date.setObjectName("checkBox_display_date")
        self.lineEdit_display_description = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_display_description.setGeometry(QtCore.QRect(190, 420, 501, 31))
        self.lineEdit_display_description.setObjectName("lineEdit_display_description")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(90, 420, 101, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton_ok = QtWidgets.QPushButton(parent=Form)
        self.pushButton_ok.setGeometry(QtCore.QRect(510, 470, 93, 28))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(parent=Form)
        self.pushButton_cancel.setGeometry(QtCore.QRect(620, 470, 93, 28))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_clear = QtWidgets.QPushButton(parent=Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(270, 470, 81, 31))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.checkBox_display_full = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_display_full.setGeometry(QtCore.QRect(360, 380, 91, 31))
        self.checkBox_display_full.setObjectName("checkBox_display_full")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_image.setText(_translate("Form", "image"))
        self.pushButton_set_image.setText(_translate("Form", "Custom background"))
        self.checkBox_display_title.setText(_translate("Form", "Title"))
        self.checkBox_display_resolution.setText(_translate("Form", "Resolution"))
        self.checkBox_display_date.setText(_translate("Form", "Date"))
        self.label_2.setText(_translate("Form", "description:"))
        self.pushButton_ok.setText(_translate("Form", "OK"))
        self.pushButton_cancel.setText(_translate("Form", "Cancel"))
        self.pushButton_clear.setText(_translate("Form", "Clear"))
        self.checkBox_display_full.setText(_translate("Form", "Full"))
